export const DATABASE_ID = process.env.NOTION_DATABASE_ID;
export const DATABASE_ID2 = process.env.NOTION_DATABASE_ID2;
export const TOKEN = process.env.NOTION_TOKEN;
export const TtokenAndJson = `?access_token=${process.env.TISTORY_TK}&output=json`;
export const BlogName = "&blogName=resee";
export const PageNumber = "&page=1";
export const BlogInfo = "https://www.tistory.com/apis/blog/info";
export const BlogList = "https://www.tistory.com/apis/post/list";
export const BlogCate = "https://www.tistory.com/apis/category/list";
